In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [26]:

df = pd.read_csv('C:\\Users\\Piku Kumar\\Desktop\\Heart\\Heart_data.csv')

In [27]:
df

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1     67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      NaN   
2     67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3     37.0  1.0  3.0     130.0  250.0  0.0      NaN    187.0    0.0      3.5   
4     41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
...    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
1587  52.0  1.0  3.0     172.0  199.0  1.0      0.0    162.0    0.0      0.5   
1588  44.0  1.0  2.0     120.0  263.0  0.0      0.0    173.0    0.0      0.0   
1589  56.0  0.0  NaN     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
1590  57.0  1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
1591  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   

      slope   ca  thal  target  
0       3.0  0.0   6.0       0  
1       2.0  3.0   3.0       2  
2       2.0  2.0   7.0       1  
3       3.0  0.0   3.0       0  
4       1.0  0.0   3.0       0  
...     ...  ...   ...     ...  
1587    1.0  0.0   7.0       1  
1588    1.0  0.0   7.0       1  
1589    2.0  0.0   3.0       1  
1590    2.0  0.0   6.0       1  
1591    2.0  3.0   3.0       2  

[1592 rows x 14 columns]

In [28]:
import numpy as np

In [29]:
df_mod = df
df_mod.fillna(df.mean(), inplace=True)

In [30]:
df_mod

age  sex        cp  trestbps   chol  fbs   restecg  thalach  exang  \
0     63.0  1.0  1.000000     145.0  233.0  1.0  2.000000    150.0    0.0   
1     67.0  1.0  4.000000     160.0  286.0  0.0  2.000000    108.0    1.0   
2     67.0  1.0  4.000000     120.0  229.0  0.0  2.000000    129.0    1.0   
3     37.0  1.0  3.000000     130.0  250.0  0.0  0.699685    187.0    0.0   
4     41.0  0.0  2.000000     130.0  204.0  0.0  2.000000    172.0    0.0   
...    ...  ...       ...       ...    ...  ...       ...      ...    ...   
1587  52.0  1.0  3.000000     172.0  199.0  1.0  0.000000    162.0    0.0   
1588  44.0  1.0  2.000000     120.0  263.0  0.0  0.000000    173.0    0.0   
1589  56.0  0.0  1.731333     140.0  294.0  0.0  2.000000    153.0    0.0   
1590  57.0  1.0  4.000000     140.0  192.0  0.0  0.000000    148.0    0.0   
1591  67.0  1.0  4.000000     160.0  286.0  0.0  2.000000    108.0    1.0   

       oldpeak  slope   ca  thal  target  
0     2.300000    3.0  0.0   6.0       0  
1     1.066496    2.0  3.0   3.0       2  
2     2.600000    2.0  2.0   7.0       1  
3     3.500000    3.0  0.0   3.0       0  
4     1.400000    1.0  0.0   3.0       0  
...        ...    ...  ...   ...     ...  
1587  0.500000    1.0  0.0   7.0       1  
1588  0.000000    1.0  0.0   7.0       1  
1589  1.300000    2.0  0.0   3.0       1  
1590  0.400000    2.0  0.0   6.0       1  
1591  1.500000    2.0  3.0   3.0       2  

[1592 rows x 14 columns]

In [31]:
X = df_mod.drop('target', axis=1)
y = df_mod['target']

In [32]:
df_mod

age  sex        cp  trestbps   chol  fbs   restecg  thalach  exang  \
0     63.0  1.0  1.000000     145.0  233.0  1.0  2.000000    150.0    0.0   
1     67.0  1.0  4.000000     160.0  286.0  0.0  2.000000    108.0    1.0   
2     67.0  1.0  4.000000     120.0  229.0  0.0  2.000000    129.0    1.0   
3     37.0  1.0  3.000000     130.0  250.0  0.0  0.699685    187.0    0.0   
4     41.0  0.0  2.000000     130.0  204.0  0.0  2.000000    172.0    0.0   
...    ...  ...       ...       ...    ...  ...       ...      ...    ...   
1587  52.0  1.0  3.000000     172.0  199.0  1.0  0.000000    162.0    0.0   
1588  44.0  1.0  2.000000     120.0  263.0  0.0  0.000000    173.0    0.0   
1589  56.0  0.0  1.731333     140.0  294.0  0.0  2.000000    153.0    0.0   
1590  57.0  1.0  4.000000     140.0  192.0  0.0  0.000000    148.0    0.0   
1591  67.0  1.0  4.000000     160.0  286.0  0.0  2.000000    108.0    1.0   

       oldpeak  slope   ca  thal  target  
0     2.300000    3.0  0.0   6.0       0  
1     1.066496    2.0  3.0   3.0       2  
2     2.600000    2.0  2.0   7.0       1  
3     3.500000    3.0  0.0   3.0       0  
4     1.400000    1.0  0.0   3.0       0  
...        ...    ...  ...   ...     ...  
1587  0.500000    1.0  0.0   7.0       1  
1588  0.000000    1.0  0.0   7.0       1  
1589  1.300000    2.0  0.0   3.0       1  
1590  0.400000    2.0  0.0   6.0       1  
1591  1.500000    2.0  3.0   3.0       2  

[1592 rows x 14 columns]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
model = LogisticRegression(solver='liblinear')

In [35]:
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [36]:
y_pred = model.predict(X_test)

In [37]:
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")

Accuracy: 0.7304075235109718
Confusion Matrix: 
[[ 93  46   1   0   0]
 [ 14 123   6   0   0]
 [  7   4  17   0   0]
 [  2   0   4   0   0]
 [  0   0   2   0   0]]


In [38]:
import pickle

In [39]:
with open('cardio_model.pkl', 'wb') as file:
    pickle.dump(model, file)